name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install thridparty
      run: |
           wget https://github.com/guodongxiaren/thirdparty/archive/refs/tags/protoc.tar.gz
           tar xvf pb.tar.gz
           
    - name: config brpc
      run: |
           THIRD_DIR=thirdparty-protoc
           export PATH=`pwd`/${THIRD_DIR}/protobuf/bin/:$PATH
           sh config_brpc.sh --headers="${THIRD_DIR}/gflags/include/ ${THIRD_DIR}/protobuf/include/" --libs="${THIRD_DIR}/gflags/lib/ ${THIRD_DIR}/protobuf/lib/"

    - name: make
      run: |
           make -j $(nproc)

      
